
/*USUARIOS*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'ADMIN', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'ADMIN', 'admin@admin.com', TRUE, NULL);
    /*1*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'Jose Manuel', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Bargueño', 'bargueno@gmail.com', TRUE, NULL);
    /*2*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'Jose Maria', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Ruiz', 'ruiz@gmail.com', TRUE, NULL);
    /*3*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'Daniel', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Troncoso', 'troncoso@gmail.com', FALSE, NULL);
    /*4*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'Jesús', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Ceacero', 'ceacero@gmail.com', FALSE, NULL);
    /*5*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), FALSE, 'Pedro', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'HERRERA', 'HERRERA@GMAIL.COM', FALSE, NULL);
    /*6*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), FALSE, 'User', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'user', 'user@user.com', TRUE, NULL);
    /*7*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), TRUE, 'Don Juan', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Bosco', '123@123.com', TRUE, NULL);
    /*8*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (NEXTVAL('hibernate_sequence'), FALSE, 'Pitón', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'Jumbotron', '321@321.com', TRUE, NULL);
    /*9*/
/*SCHOOL*/
INSERT INTO SCHOOL
    (ID, ADDRESS, NAME, SCHOOL_CODE)
VALUES
    (NEXTVAL('hibernate_sequence'), 'CONDE DE BUSTILLOS', 'SALESIANOS TRIANA', '0001-SALTRI');
    /*10*/

/*TIME_ZONE*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '08:00', '08:00:00');
/*11*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '09:00', '09:00:00');
/*12*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '10:00', '10:00:00');
/*13*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '11:30', '11:30:00');
/*14*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '12:30', '12:30:00');
/*15*/
INSERT INTO TIME_ZONE
    (ID, NAME, TIME)
VALUES(NEXTVAL('hibernate_sequence'), '13:30', '13:30:00');
/*16*/
/*ROOM CATEGORY*/

INSERT INTO ROOM_CATEGORY
    (ID, CATEGORY_NAME)
VALUES(NEXTVAL('hibernate_sequence'), 'INFORMÁTICA');
/*17*/
INSERT INTO ROOM_CATEGORY
    (ID, CATEGORY_NAME)
VALUES(NEXTVAL('hibernate_sequence'), 'LABORATORIO');
/*18*/
INSERT INTO ROOM_CATEGORY
    (ID, CATEGORY_NAME)
VALUES(NEXTVAL('hibernate_sequence'), 'TALLER');
/*19*/
INSERT INTO ROOM_CATEGORY
    (ID, CATEGORY_NAME)
VALUES(NEXTVAL('hibernate_sequence'), 'DEPORTIVA');
/*20*/
/*ROOM*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'AULA-01', 10, 17);
/*21*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'PISTA FÚTBOL', 10, 20);
/*22*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'PISTA BALONMANO', 10, 20);
/*23*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'PISTA BALONCESTO', 10, 20);
/*24*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'ELECTRÓNICA-01', 10, 19);
/*25*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'LABORATORIO-BIO-01', 10, 18);
/*26*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(NEXTVAL('hibernate_sequence'), 'LABORATORIO-QUIM-01', 10, 18);
/*27*/
/*RESERVED_DATE*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('12/10/2019', 'DD/MM/YYYY'));
    /*28*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('01/11/2019', 'DD/MM/YYYY'));
    /*29*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('06/12/2019', 'DD/MM/YYYY'));
    /*30*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('09/12/2019', 'DD/MM/YYYY'));
    /*31*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('25/12/2019', 'DD/MM/YYYY'));
    /*32*/
INSERT INTO RESERVED_DATE
    (ID, DATE)
VALUES
    (NEXTVAL('hibernate_sequence'), TO_DATE('04/10/2019', 'DD/MM/YYYY'));
    /*33*/


/*RESERVECHECKER*/
INSERT INTO RESERVE_CHECKER
    (ID, WEEKEND_ON)
VALUES(NEXTVAL('hibernate_sequence'), FALSE);
/*34*/
/*RESERVE*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('03/10/2019', 'DD/MM/YYYY'), 8, 21, NULL, 13);
/*35*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('02/10/2019', 'DD/MM/YYYY'), 3, 22, NULL, 14);
/*36*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('02/10/2019', 'DD/MM/YYYY'), 2, 22, NULL, 15);
/*37*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('02/10/2019', 'DD/MM/YYYY'), 1, 22, NULL, 16);
/*38*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('01/10/2019', 'DD/MM/YYYY'), 7, 23, NULL, 15);
/*39*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('27/09/2019', 'DD/MM/YYYY'), 8, 23, NULL, 11);
/*40*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('27/09/2019', 'DD/MM/YYYY'), 9, 23, NULL, 12);
/*41*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('27/09/2019', 'DD/MM/YYYY'), 9, 23, NULL, 13);
/*42*/
INSERT INTO RESERVE
    (ID, DATE, RESERVE_USER_ID, RESERVED_ROOM_ID, SCHOOL_ID, TIME_ZONE_ID)
VALUES(NEXTVAL('hibernate_sequence'), TO_DATE('27/09/2019', 'DD/MM/YYYY'), 8, 24, NULL, 13);
/*43*/
